version: '2'
services:
  meta-exporter:
    build: ./meta-exporter
    network_mode: 'host'
    environment:
      - 'SCRAPE_URLS=9100/metrics,9101/probe?target=api.balena-cloud.com/ping&module=http_2xx'
      - 'META_EXPORTER_PORT=80'
  node-exporter:
    build: ./examples/node-exporter
    environment:
      - 'SCRAPE_PORT=9100'
    ports:
      - '9100:9100'
  blackbox-exporter:
    build: ./examples/blackbox-exporter
    environment:
      - 'SCRAPE_PORT=9101'
    ports:
      - '9101:9101'
