FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine:edge as build
RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories
RUN install_packages prometheus-node-exporter

FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine:3.11-run
COPY --from=build /usr/bin/node_exporter /bin/node_exporter
COPY entry.sh /bin/
CMD ["/bin/entry.sh"]
