FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-node:12.16
COPY src /usr/src/app/src
COPY entry.sh package.json package-lock.json /usr/src/app/
WORKDIR /usr/src/app
RUN npm ci && npm run build
CMD [ "/usr/src/app/entry.sh" ]
