FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-golang:1.11.2
WORKDIR /app
ADD . /app/
RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories && \
    apk add --no-cache prometheus-node-exporter
#RUN install_packages git make curl && \
#   go clean -modcache && \
#   go get github.com/prometheus/node_exporter && \
#   cd ${GOPATH-$HOME/go}/src/github.com/prometheus/node_exporter && \
#   make
CMD ["/app/entry.sh"]
